import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('orders').del();

  await knex('orders').insert([
    {
      id: 1,
      user_id: 1,
      completed: false,
      cancelled: false,
      kitchen_cancelled: false,
      kitchen_accepted: true,
      kitchen_dispatched: false,
      kitchen_dispatched_time: null,
      completed_time: null,
      rider_id: 1,
      kitchen_prepared: true,
      rider_assigned: true,
      paid: false,
      order_code: 'ORD123ABC',
      order_change: 500.0,
      calculated_order_id: 1,
      kitchen_verified_time: null,
      kitchen_completed_time: null,
      shop_accepted: true,
      shop_prepared: false,
      no_of_mealbags_delivered: 0,
      no_of_drinks_delivered: 0,
      rider_started_time: null,
      rider_started: false,
      rider_arrived_time: null,
      rider_arrived: false,
      is_failed_trip: false,
      failed_trip_details: {},
      box_number: 'BX-001',
      shelf_id: 1,
      scheduled: false,
      confirmed_by_id: null,
      completed_by_id: null,
      scheduled_delivery_date: null,
      scheduled_delivery_time: null,
      is_hidden: false,
      order_type_id: 's1',
    },
    {
      id: 2,
      user_id: 2,
      completed: true,
      cancelled: false,
      kitchen_cancelled: false,
      kitchen_accepted: true,
      kitchen_dispatched: true,
      kitchen_dispatched_time: knex.fn.now(),
      completed_time: knex.fn.now(),
      rider_id: 2,
      kitchen_prepared: true,
      rider_assigned: true,
      paid: true,
      order_code: 'ORD456DEF',
      order_change: 0,
      calculated_order_id: 2,
      kitchen_verified_time: knex.fn.now(),
      kitchen_completed_time: knex.fn.now(),
      shop_accepted: true,
      shop_prepared: true,
      no_of_mealbags_delivered: 2,
      no_of_drinks_delivered: 1,
      rider_started_time: knex.fn.now(),
      rider_started: true,
      rider_arrived_time: knex.fn.now(),
      rider_arrived: true,
      is_failed_trip: false,
      failed_trip_details: {},
      box_number: 'BX-002',
      shelf_id: 2,
      scheduled: true,
      confirmed_by_id: 3,
      completed_by_id: 4,
      scheduled_delivery_date: '2025-07-21',
      scheduled_delivery_time: '14:30:00',
      is_hidden: false,
      order_type_id: 's1',
    },
  ]);
  await knex.raw(
    `SELECT setval('orders_id_seq', (SELECT MAX(id) FROM orders))`,
  );
}
